# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pop_win_choose.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(453, 422)
        self.lv_profit_list = QtWidgets.QListView(Form)
        self.lv_profit_list.setGeometry(QtCore.QRect(10, 10, 431, 371))
        self.lv_profit_list.setObjectName("lv_profit_list")
        self.btn_choose = QtWidgets.QPushButton(Form)
        self.btn_choose.setGeometry(QtCore.QRect(280, 390, 75, 24))
        self.btn_choose.setObjectName("btn_choose")
        self.btn_close = QtWidgets.QPushButton(Form)
        self.btn_close.setGeometry(QtCore.QRect(360, 390, 75, 24))
        self.btn_close.setObjectName("btn_close")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "从以下行情数据中选择"))
        self.btn_choose.setText(_translate("Form", "选择"))
        self.btn_close.setText(_translate("Form", "关闭"))
